.gitignore
editor/dist/css.css
editor/dist/img/logo.svg
editor/dist/img/splash.svg
editor/src/projectSelector/ProjectSelector.js

feat: New splash screen

---

.eslintignore
.github/workflows/ci.yml
scripts/dev.js

Ci caching

---

editor/builtInAssets/shaders/wgsl/ClusteredCompute/ComputeClusterLights.wgsl

fix(wgsl): Rename deprecated reserved word

---

editor/src/projectSelector/ProjectSelector.js

fix(projects): Don't show db projects without an indexedDb in the project selector

---

editor/src/ui/TreeView.js
editor/src/windowManagement/contentWindows/ProjectContentWindow.js

fix: Remove drag data when releasing dragged assets

---

editor/src/tasks/TaskManager.js
editor/src/windowManagement/contentWindows/ContentWindowProject.js
test/unit/editor/src/tasks/TaskManager.test.js

refactor: Automatically add create tasks to context menu

---

editor/src/assets/ProjectAsset.js
editor/src/tasks/autoRegisterTaskTypes.js
editor/src/tasks/task/TaskBundleAssets.js
editor/src/tasks/workers/bundleAssets/bundle.js
editor/src/tasks/workers/bundleAssets/mod.js
editor/src/util/fileSystems/EditorFileSystem.js
editor/src/util/fileSystems/MemoryEditorFileSystem.js
editor/src/util/fileSystems/MemoryFileSystemWritableFileStream.js
importmap.json
src/util/TypedMessenger.js
test/unit/editor/src/tasks/TaskManager.test.js
test/unit/editor/src/tasks/shared/basicWorker.js
test/unit/editor/src/tasks/task/TaskBundleAssets.test.js
test/unit/editor/src/util/fileSystems/MemoryEditorFileSystem/writeFileStream.test.js
test/unit/src/util/TypedMessenger.test.js

feat: Use a task for bundling assets

---

scripts/DevServer.js
scripts/test.js
test/e2e/shared/browser.js

test: Use a random port for the test server

---

editor/src/ui/DroppableGui.js
test/unit/editor/src/ui/DroppableGui/dragEvents.test.js
test/unit/shared/helperTypes.d.ts

feat: Allow specifying ProjectAssetTypes as supportedAssetTypes in droppable guis

---

editor/src/ui/DroppableGui.js
test/unit/editor/src/ui/DroppableGui/dragEvents.test.js

fix: Correctly handle droppable guis with ProjectAssetTypes without a live asset

---

editor/builtInAssets/assetSettings.json
editor/builtInAssets/buildSupport/basicIndex.html
editor/src/assets/autoRegisterAssetTypes.js
editor/src/assets/projectAssetType/ProjectAssetTypeHtml.js
editor/src/tasks/autoRegisterTaskTypes.js
editor/src/tasks/task/TaskGenerateHtml.js
editor/src/tasks/task/TaskGenerateServices.js
test/unit/editor/src/tasks/task/TaskGenerateHtml.test.js

feat(tasks): Add a task for generating html from a template

---

src/core/Entity.js
test/unit/src/core/Entity/hierarchy.test.js

feat(core): Support for traversing entities with a filter

---

editor/src/assets/projectAssetType/ProjectAssetTypeEntity.js
editor/src/tasks/task/TaskGenerateServices.js
src/core/Entity.js
test/unit/editor/src/assets/projectAssetType/EntityProjectAssetType.test.js
test/unit/editor/src/tasks/task/TaskGenerateServices.test.js

feat(tasks): Register used component types to entity asset loader

---

.github/codecov.yml
.github/workflows/ci.yml
.vscode/settings.json
scripts/test.js

chore: Setup codecov

---

editor/scripts/build.js
importmap.json

chore: Minify release builds

---

editor/src/Editor.js
editor/src/ui/TreeView.js
editor/src/windowManagement/EditorWindow.js
editor/src/windowManagement/EditorWindowTabs.js
editor/src/windowManagement/WindowManager.js
editor/src/windowManagement/contentWindows/ContentWindow.js
editor/src/windowManagement/contentWindows/ContentWindowBuildView.js
editor/src/windowManagement/contentWindows/ContentWindowBuiltInAssets.js
editor/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
editor/src/windowManagement/contentWindows/ContentWindowOutliner.js
editor/src/windowManagement/contentWindows/ContentWindowProject.js
importmap.json
test/unit/editor/src/ui/TreeView/events.test.js
test/unit/editor/src/windowManagement/contentWindows/ProjectContentWindow.test.js

feat: Selection manager improvements

---

.github/workflows/deploy-pr.yml
editor/src/util/fileSystems/IndexedDbEditorFileSystem.js
test/unit/editor/shared/FakeIndexedDbUtil.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/delete.test.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/misc.test.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/move.test.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/shared.js

fix(File Systems): Implement file locking

---

.eslintrc.cjs
editor/src/css.css
editor/src/tasks/task/TaskGenerateHtml.js
editor/src/ui/DropDownGui.js
editor/src/ui/PathGui.js
editor/src/ui/TextGui.js
editor/src/ui/propertiesTreeView/PropertiesTreeViewEntry.js
editor/src/ui/propertiesTreeView/types.ts
editor/src/util/colorizerFilters/ColorizerFilter.js
editor/src/util/colorizerFilters/ColorizerFilterManager.js
editor/static/icons/generic/pathArrow.svg
scripts/.eslintrc.json
test/e2e/editor/src/ui/PathGui/PathGui.test.js
test/e2e/editor/src/ui/PathGui/browserContent/basic.js

42-Add-a-gui-for-file/folder-selection

---

.eslintrc.cjs
editor/src/assets/AssetManager.js
editor/src/css.css
editor/src/keyboardShortcuts/autoRegisterShortcutCommands.js
editor/src/keyboardShortcuts/autoRegisterShortcutConditions.js
editor/src/tasks/task/TaskGenerateHtml.js
editor/src/ui/DropDownGui.js
editor/src/ui/DroppableGui.js
editor/src/ui/PathGui.js
editor/src/ui/TextGui.js
editor/src/ui/contextMenus/ContextMenu.js
editor/src/ui/contextMenus/ContextMenuItem.js
editor/src/ui/propertiesTreeView/PropertiesTreeViewEntry.js
editor/src/ui/propertiesTreeView/types.ts
editor/src/util/colorizerFilters/ColorizerFilter.js
editor/src/util/colorizerFilters/ColorizerFilterManager.js
editor/static/icons/generic/pathArrow.svg
importmap.json
scripts/.eslintrc.json
test/e2e/editor/src/ui/PathGui/PathGui.test.js
test/e2e/editor/src/ui/PathGui/browserContent/basic.js
test/unit/editor/shared/contextMenuHelpers.js
test/unit/editor/src/ui/DroppableGui/contextMenu.test.js
test/unit/editor/src/ui/DroppableGui/embeddedAssets.test.js
test/unit/editor/src/ui/DroppableGui/misc.test.js
test/unit/editor/src/ui/DroppableGui/pasteUuid.test.js
test/unit/editor/src/ui/DroppableGui/setGetValue.test.js
test/unit/editor/src/ui/DroppableGui/shared.js

97-Support-for-pasting-asset-uuids-in-droppable-guis

---

editor/src/ui/DroppableGui.js
test/unit/editor/src/ui/DroppableGui/shared.js

refactor(DroppableGui): Remove dependencies object

---

editor/src/keyboardShortcuts/autoRegisterShortcutCommands.js
editor/src/ui/DroppableGui.js
test/unit/editor/src/ui/DroppableGui/misc.test.js
test/unit/editor/src/ui/DroppableGui/pasteUuid.test.js
test/unit/editor/src/ui/DroppableGui/shared.js

refactor(DroppableGui): Use shortcut manager for unlinking values

---

editor/src/util/fileSystems/IndexedDbEditorFileSystem.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/misc.test.js

fix(IndexedDbEditorFileSystem): Better handling of calling many operations at once

---

editor/src/projectSelector/ProjectManager.js
editor/src/projectSelector/ProjectSelector.js
test/e2e/editor/shared/assets.js
test/e2e/editor/shared/project.js
test/e2e/editor/shared/treeView.js
test/e2e/editor/src/projectSelector/projectSelector.test.js
test/e2e/shared/util.js

feat(projects): Create a new empty project when deleting the currently open one

---

editor/src/css.css
editor/src/windowManagement/contentWindows/ContentWindow.js
editor/src/windowManagement/contentWindows/ContentWindowBuildView.js
editor/src/windowManagement/contentWindows/ContentWindowEntityEditor.js

fix(windowmanager): Hide scrollbars in buildview and entityeditor

---

editor/src/assets/AssetManager.js
editor/src/assets/InternallyCreatedAsset.js
editor/src/assets/ProjectAsset.js
editor/src/ui/DroppableGui.js
editor/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/editor/src/assets/AssetManager/internallyCreatedAssets.test.js
test/unit/editor/src/assets/ProjectAsset/misc.test.js
test/unit/editor/src/ui/DroppableGui/pasteUuid.test.js
test/unit/editor/src/ui/DroppableGui/shared.js

fix: Make asset uuid persistent when pasting uuid

---

.github/workflows/build.yml
.github/workflows/ci.yml
deno.json
scripts/dev.js

chore: Upgrade to Deno 1.25.3

---

.github/workflows/build.yml
.github/workflows/ci.yml
.gitignore
.vscode/settings.json
scripts/dev.js

chore: Download TypeScript in dev script

---

.vscode/extensions.json
.vscode/settings.json
deno.json
scripts/lint.js

chore: Support linting using renda-dev extension

---

.github/workflows/ci.yml
importmap.json
scripts/dev.js
scripts/test.js

chore: Download puppeteer browser when running e2e tests

---

editor/src/Editor.js
editor/src/assets/AssetManager.js
editor/src/projectSelector/ProjectManager.js
editor/src/util/fileSystems/EditorFileSystem.js
editor/src/util/fileSystems/FsaEditorFileSystem.js
editor/src/util/fileSystems/IndexedDbEditorFileSystem.js
editor/src/util/fileSystems/MemoryEditorFileSystem.js
editor/src/windowManagement/contentWindows/ContentWindowProject.js
test/unit/editor/src/assets/AssetManager/misc.test.js
test/unit/editor/src/util/fileSystems/FsaEditorFileSystem/createDir.test.js
test/unit/editor/src/util/fileSystems/FsaEditorFileSystem/delete.test.js
test/unit/editor/src/util/fileSystems/FsaEditorFileSystem/misc.test.js
test/unit/editor/src/util/fileSystems/FsaEditorFileSystem/move.test.js
test/unit/editor/src/util/fileSystems/FsaEditorFileSystem/watching.test.js
test/unit/editor/src/util/fileSystems/FsaEditorFileSystem/writeFile.test.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/delete.test.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/misc.test.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/move.test.js
test/unit/editor/src/util/fileSystems/MemoryEditorFileSystem/createDir.test.js
test/unit/editor/src/util/fileSystems/MemoryEditorFileSystem/misc.test.js
test/unit/editor/src/util/fileSystems/MemoryEditorFileSystem/writeFile.test.js
test/unit/editor/src/util/fileSystems/shared.js
test/unit/editor/src/windowManagement/contentWindows/ContentWindowProject.test.js

feat(file systems): Support for events when changing files internally

---

editor/src/windowManagement/contentWindows/ContentWindow.js

fix: Apply scrollable class to the content window

---

editor/src/ui/contextMenus/ContextMenuItem.js

fix: Fix broken context menu icon paths

---

editor/src/tasks/TaskManager.js
editor/src/tasks/task/TaskBuildApplication.js

refactor: Better types for runTask

---

editor/src/windowManagement/EditorWindowTabs.js
editor/src/windowManagement/WorkspaceManager.js

feat: Support for cloning a workspace

---

editor/src/windowManagement/WorkspaceManager.js

fix: Delete workspace data when deleting a workspace

---

importmap.json
scripts/dev.js

chore: Upgrade tsc_helper

---

editor/src/assets/projectAssetType/ProjectAssetTypeEntity.js
src/util/binarySerialization.js

fix: Resolve asset links when bundling entity components

---

src/math/Vec2.js
src/math/Vec3.js
test/unit/src/math/Vec2.test.js
test/unit/src/math/Vec3.test.js

feat(math): Add cross, shortestAngleTo and clockwiseAngleTo

---

src/math/Vec2.js
src/math/Vec3.js
src/math/Vec4.js
test/unit/src/math/Vec2.test.js
test/unit/src/math/Vec3.test.js
test/unit/src/math/Vec4.test.js

feat(math): Add static vector math functions

---

editor/src/windowManagement/contentWindows/ContentWindowProject.js

feat: Make asset uuid persistent when copying via context menu

---

src/math/Quat.js
src/util/OrbitControls.js
test/unit/src/math/Quat.test.js

fix: Make Quat.rotateVector return correct values

---

.github/workflows/build.yml
.github/workflows/deploy-canary.yml
.github/workflows/deploy-pr.yml

chore: Provide commit sha when deploying canary

---

src/math/Quat.js

feat(math): Add Quat.inverse()

---

src/math/Quat.js

feat(math): Add Quat.identity

---

editor/src/css.css
editor/src/projectSelector/ProjectSelector.js

feat: Use a better font

---

editor/src/componentGizmos/gizmos/ComponentGizmosCamera.js

fix: Update projection matrix when rendering camera gizmo

---

editor/src/ui/TreeView.js

fix: Allow deselecting treeview rows by clicking them

---

test/e2e/editor/src/projectSelector/projectSelector.test.js

I highly doubt that this will fix it, but let's find out
Fixes #236

test: Disable navigation timeout on e2e test

---

src/math/Quat.js
src/math/Vec2.js
src/math/Vec3.js
src/math/Vec4.js
test/unit/shared/asserts.js
test/unit/shared/asserts.test.js
test/unit/src/math/Quat.test.js
test/unit/src/math/Vec2.test.js
test/unit/src/math/Vec3.test.js
test/unit/src/math/Vec4.test.js

feat: Add toString to Vec and Quat

---

editor/src/assets/projectAssetType/ProjectAssetTypeMaterialMap.js
src/assets/assetLoaderTypes/AssetLoaderTypeMaterialMap.js
src/util/binarySerialization.js
src/util/binarySerializationTypes.ts
src/util/util.js
test/unit/editor/src/assets/ProjectAsset/getBundledAssetData.test.js
test/unit/editor/src/assets/projectAssetType/ProjectAssetTypeMaterialMap.test.js
test/unit/src/util/binarySerialization/unions.test.js

feat: Material map mapped values serialization for asset bundles

---

test/unit/src/util/binarySerialization/unions.test.js

test: Add test for primitive types in union arrays

---

editor/src/ui/propertiesTreeView/PropertiesTreeViewEntry.js
editor/src/ui/propertiesTreeView/types.ts

feat: Add support for tooltips on PropertiesTreeViewEntries

---

editor/src/assets/projectAssetType/ProjectAssetTypeSampler.js
src/assets/assetLoaderTypes/AssetLoaderTypeSampler.js
src/assets/assetLoaderTypes/AssetLoaderTypes.js
test/unit/src/assets/assetLoaderTypes/AssetLoaderTypeSampler.test.js

feat: Add asset loader for samplers

---

src/assets/assetLoaderTypes/AssetLoaderTypeMaterialMap.js
test/unit/editor/src/assets/projectAssetType/ProjectAssetTypeMaterialMap.test.js

fix: Correctly serialize material maps with color textures

---

src/assets/assetLoaderTypes/AssetLoaderTypeMaterialMap.js
src/util/binarySerialization.js
src/util/binarySerializationTypes.ts
test/unit/editor/src/assets/projectAssetType/ProjectAssetTypeMaterialMap.test.js
test/unit/src/util/binarySerialization/binaryToObjectWithAssetLoader.test.js

feat: binaryToObjectWithAssetLoader improvements

---

editor/src/tasks/TaskManager.js
editor/src/tasks/task/Task.js
editor/src/tasks/task/TaskBuildApplication.js
editor/src/tasks/task/TaskGenerateServices.js
editor/src/tasks/workers/buildApplication/mod.js
src/rendering/renderers/webGpu/WebGpuRenderer.js
test/unit/editor/src/tasks/task/TaskGenerateServices.test.js

feat: Initialize renderer in generated services script

---

editor/scripts/build.js
editor/src/misc/ServiceWorkerManager.js
editor/src/network/editorConnections/internalDiscovery/internalDiscoveryMain.js
scripts/dev.js

fix: Make rollup-plugin-resolve-url-objects work again

---

editor/scripts/build.js
editor/src/editorDefines.js
editor/src/tasks/workers/bundleScripts/resolvePlugin.js
importmap.json
scripts/build.js

feat: Use a different engine source path in dev vs production

---

editor/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js

feat: Mark project as worth saving when pressing play

---

editor/src/Editor.js
editor/src/misc/ServiceWorkerManager.js
test/unit/editor/src/misc/ServiceWorkerManager.test.js

test: Add tests for ServiceWorkerManager

---

editor/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
src/components/builtIn/CameraComponent.js
src/rendering/renderers/webGpu/WebGpuRenderer.js
test/unit/editor/src/components/builtIn/CameraComponent.test.js

feat: Auto update camera aspect ratio based on dom target size

---

editor/src/ui/propertiesTreeView/PropertiesTreeViewEntry.js

feat: Show label text in a tooltip when hovering over PropertiesTreeViewEntries

---

editor/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
editor/src/windowManagement/contentWindows/ContentWindowEntityEditor.js

feat: Don't render cameras in the build view

---

src/components/builtIn/LightComponent.js
test/unit/src/core/Entity/clone.test.js

fix: Make sure light components get the correct type applied

---

src/util/binarySerialization.js
test/unit/src/util/binarySerialization/serialization.test.js

feat: Throw when binary serialization receives duplicate name ids

---

editor/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
src/core/Entity.js

fix: Update child gizmos when dragging a parent

---

.github/workflows/build-pr.yml
.github/workflows/build.yml
deno.json
editor/scripts/build.js
editor/src/editorDefines.js
editor/src/misc/thirdPartyLicenses.js
editor/src/styles/styles.js
editor/src/windowManagement/autoRegisterContentWindows.js
editor/src/windowManagement/contentWindows/ContentWindowAbout.css
editor/src/windowManagement/contentWindows/ContentWindowAbout.js
editor/static/icons/contentWindowTabs/about.svg
scripts/dev.js

Add about window with build info

---

editor/src/editorDefines.js
editor/src/misc/ServiceWorkerManager.js
scripts/buildEditor.js
test/unit/editor/src/misc/ServiceWorkerManager.test.js

fix: Use correct engine import map value for generated html

---

editor/src/keyboardShortcuts/KeyboardShortcutManager.js
editor/src/keyboardShortcuts/ShorcutConditionValueSetter.js
editor/src/keyboardShortcuts/ShortcutCondition.js
editor/src/keyboardShortcuts/autoRegisterShortcutConditions.js
editor/src/ui/TreeView.js
editor/src/windowManagement/EditorWindow.js
editor/src/windowManagement/EditorWindowTabs.js
editor/src/windowManagement/WindowManager.js
editor/src/windowManagement/WorkspaceManager.js
editor/src/windowManagement/contentWindows/ContentWindow.js
editor/src/windowManagement/contentWindows/ContentWindowBuiltInAssets.js
editor/src/windowManagement/contentWindows/ContentWindowOutliner.js
editor/src/windowManagement/contentWindows/ContentWindowProject.js
importmap.json
test/unit/editor/shared/mockKeyboardShortcutManager.js
test/unit/editor/src/ui/DroppableGui/shared.js
test/unit/editor/src/windowManagement/WindowManager.test.js
test/unit/editor/src/windowManagement/contentWindows/ContentWindowProject.test.js

Use last clicked content window for active selection group

---

editor/src/keyboardShortcuts/ShortcutCommand.js
editor/src/keyboardShortcuts/conditionExpressions.js
test/unit/editor/src/keyboardShortcuts/ShortcutCommand.test.js
test/unit/editor/src/keyboardShortcuts/conditionExpressions.test.js

feat: Support logic in shortcut conditions

---

.eslintignore
editor/src/Editor.js
editor/src/keyboardShortcuts/autoRegisterShortcutCommands.js
editor/src/main.js
editor/src/misc/HistoryManager.js
editor/src/styles/denoShadowStyles.js
editor/src/styles/documentStyles.js
editor/src/styles/shadowStyles.js
editor/src/styles/styles.js
editor/src/windowManagement/WindowManager.js
editor/src/windowManagement/autoRegisterContentWindows.js
editor/src/windowManagement/contentWindows/ContentWindowHistory.css
editor/src/windowManagement/contentWindows/ContentWindowHistory.js
editor/src/windowManagement/contentWindows/ContentWindowOutliner.js
editor/src/windowManagement/windowManagement.css
editor/static/icons/contentWindowTabs/about.svg
editor/static/icons/contentWindowTabs/history.svg
editor/static/icons/redo.svg
editor/static/icons/undo.svg
importmap.json
src/core/Entity.js
test/unit/editor/src/misc/HistoryManager.test.js
test/unit/editor/src/windowManagement/WindowManager.test.js
test/unit/editor/src/windowManagement/contentWindows/ContentWindowHistory.test.js

feat: History management

---

editor/src/tasks/TaskManager.js
editor/src/tasks/task/Task.js
editor/src/tasks/task/TaskBundleAssets.js
test/unit/editor/src/tasks/TaskManager.test.js
test/unit/editor/src/tasks/task/TaskBundleAssets.test.js

feat: Add touchedPaths to bunlde assets task

---

.github/workflows/build.yml
.github/workflows/ci.yml
test/unit/editor/devSocket/src/BuiltInAssetManager.test.js

374-upgrade-to-deno-130

---

src/math/Vec2.js
src/math/Vec3.js
src/math/Vec4.js
test/unit/src/math/Vec2.test.js
test/unit/src/math/Vec3.test.js

200-Add-`Vec3clockwiseAngleTo`

---

src/gizmos/draggables/RotateAxisGizmoDraggable.js
src/gizmos/draggables/TranslateAxisGizmoDraggable.js
src/gizmos/gizmos/TranslationGizmo.js
src/math/Quat.js
src/math/Vec3.js
src/util/OrbitControls.js
test/unit/src/math/Quat.test.js
test/unit/src/math/Vec3.test.js

feat: Rename Quat.rotateVector to Vec3.rotate

---

editor/src/main.js
editor/src/util/e2e/mod.js
editor/src/util/e2e/treeView.js
test/e2e/editor/shared/assets.js
test/e2e/editor/shared/treeView.js
test/e2e/editor/src/projectSelector/projectSelector.ignored test.js

test: Add utility functions for e2e tests

---

src/inspector/InternalDiscoveryManager.js
src/util/TypedMessenger.js
studio/src/misc/ServiceWorkerManager.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryIframeMain.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryWorkerMain.js
studio/src/tasks/task/TaskBuildApplication.js
studio/src/tasks/task/TaskBundleAssets.js
studio/src/tasks/task/TaskBundleScripts.js
studio/src/tasks/workers/buildApplication/mod.js
studio/src/tasks/workers/bundleAssets/bundle.js
studio/src/tasks/workers/bundleScripts/bundle.js
studio/sw.js
test/unit/src/util/TypedMessenger/TypedMessenger.test.js
test/unit/src/util/TypedMessenger/shared/workerWithInitialize.js
test/unit/studio/src/misc/ServiceWorkerManager.test.js
test/unit/studio/src/tasks/TaskManager.test.js

feat!: Replace TypedMessenger.send and sendWithTransfer with a proxy object

---

test/e2e/editor/shared/assets.js
test/e2e/editor/shared/contentWindows/outliner.js
test/e2e/editor/shared/contextMenu.js
test/e2e/editor/shared/droppableGui.js
test/e2e/editor/shared/project.js
test/e2e/editor/shared/reloadPage.js
test/e2e/editor/shared/studio.js
test/e2e/editor/shared/waitSeconds.js
test/e2e/editor/src/assets/embeddedAssets.test.js
test/e2e/editor/src/assets/projectAssetType/ProjectAssetTypeWebGpuPipelineConfig.test.js
test/e2e/editor/src/projectSelector/projectSelector.test.js
test/e2e/editor/src/windowManagement/contentWindows/OutlinerContentWindow.test.js
test/e2e/shared/log.js

It seems like test steps are not logged when a test hangs (https://github.com/denoland/deno/issues/17788)
This change should make it easier to figure out what's causing #328

test: Remove test steps from e2e tests

---

scripts/test.js
scripts/testArgs.js
studio/src/util/e2e/treeView.js
test/e2e/shared/browser.js
test/readme.md

test: Test arguments improvements

---

studio/src/preferences/PreferencesManager.js
studio/src/preferences/preferencesLocation/ContentWindowPreferencesLocation.js
studio/src/preferences/preferencesLocation/PreferencesLocation.js
studio/src/projectSelector/ProjectManager.js
studio/src/util/fileSystems/MemoryStudioFileSystem.js
studio/src/windowManagement/WindowManager.js
studio/src/windowManagement/contentWindows/ContentWindow.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
test/unit/studio/src/preferences/PreferencesManager.test.js
test/unit/studio/src/projectSelector/ProjectManager.test.js
test/unit/studio/src/util/fileSystems/all/tests/delete.test.js
test/unit/studio/src/windowManagement/WindowManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowConnections.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowHistory.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowProject.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowProperties.test.js

feat: Add contentwindow-project preference locations

---

importmap.json
test/unit/studio/src/ui/NumericGui.test.js

test: Fix broken NumericGui unit tests

---

studio/src/Studio.js
studio/src/misc/GestureInProgressManager.js
studio/src/windowManagement/SplitStudioWindow.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
test/unit/studio/src/misc/GestureInProgressManager.test.js
test/unit/studio/src/windowManagement/SplitStudioWindow.test.js

feat: Add disable pointer events on iframes while resizing windows

---

studio/src/windowManagement/WindowManager.js
studio/src/windowManagement/WorkspaceManager.js
studio/src/windowManagement/contentWindows/ContentWindowAbout.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
studio/src/windowManagement/contentWindows/ContentWindowBuiltInAssets.js
studio/src/windowManagement/contentWindows/ContentWindowConnections.js
studio/src/windowManagement/contentWindows/ContentWindowDefaultAssetLinks.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowHistory.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
studio/src/windowManagement/contentWindows/ContentWindowProject.js
studio/src/windowManagement/contentWindows/ContentWindowProperties.js
test/e2e/studio/shared/assets.js
test/e2e/studio/shared/contentWindows/connections.js
test/e2e/studio/shared/contentWindows/outliner.js
test/e2e/studio/shared/contentWindows/properties.js
test/e2e/studio/shared/project.js
test/unit/studio/src/windowManagement/WindowManager.test.js

feat: Enforce namespaces in content window types

---

studio/src/assets/projectAssetType/ProjectAssetType.js
studio/src/assets/projectAssetType/ProjectAssetTypeEntity.js
studio/src/assets/projectAssetType/ProjectAssetTypeGltf.js
studio/src/propertiesAssetContent/PropertiesAssetContentMaterial.js
studio/src/propertiesWindowContent/PropertiesWindowContentEntity.js
studio/src/propertiesWindowContent/PropertiesWindowContentManager.js
studio/src/windowManagement/WindowManager.js
studio/src/windowManagement/autoRegisterContentWindows.js
studio/src/windowManagement/contentWindows/ContentWindow.js
studio/src/windowManagement/contentWindows/ContentWindowAbout.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
studio/src/windowManagement/contentWindows/ContentWindowBuiltInAssets.js
studio/src/windowManagement/contentWindows/ContentWindowConnections.js
studio/src/windowManagement/contentWindows/ContentWindowDefaultAssetLinks.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowHistory.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
studio/src/windowManagement/contentWindows/ContentWindowProject.js
studio/src/windowManagement/contentWindows/ContentWindowProperties.js
test/e2e/studio/shared/contentWindows.js
test/unit/studio/src/assets/projectAssetType/ProjectAssetType.test.js
test/unit/studio/src/assets/projectAssetType/ProjectAssetTypeEntity.test.js
test/unit/studio/src/propertiesAssetContent/MaterialPropertiesAssetContent.test.js
test/unit/studio/src/windowManagement/WindowManager.test.js

feat: Support for passing strings to ContentWindow functions

---

src/rendering/renderers/webGpu/ClusterComputeManager.js
src/rendering/renderers/webGpu/WebGpuRenderer.js
studio/builtInAssets/shaders/wgsl/ClusteredCompute/ClusterLightsStruct.wgsl
studio/builtInAssets/shaders/wgsl/materials/frag.wgsl

fix: Use view bindgroup for writing light indices in clustered compute shader

---

src/rendering/renderers/webGpu/WebGpuRenderer.js
studio/src/componentGizmos/gizmos/ComponentGizmosCamera.js

fix: Use correct alignment in view uniforms

---

studio/builtInAssets/gizmos/billboard gizmo/vert.wgsl

fix: Render billboard gizmo vertices at z 0

---

.eslintignore
importmap.json
studio/src/main.js
studio/src/studioInstance.js
studio/src/styles/denoShadowStyles.js
studio/src/styles/dummyStylesModule.js
studio/src/styles/initialLoad.css
studio/src/styles/projectSelectorStyles.js
studio/src/styles/readme.md
studio/src/styles/studio.css
studio/src/styles/studioStyles.js

feat: Lazy load studio styles

---

studio/src/keyboardShortcuts/KeyboardShortcutManager.js
studio/src/keyboardShortcuts/ShortcutCommand.js
studio/src/keyboardShortcuts/autoRegisterShortcutCommands.js
test/unit/studio/src/keyboardShortcuts/KeyboardShortcutManager.test.js

feat: Disable keyboard shortcuts when a text field has focus

---

studio/src/network/studioConnections/StudioConnectionsManager.js
studio/src/network/studioConnections/internalDiscovery/readme.md
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
test/unit/studio/src/network/studioConnections/StudioConnectionsManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowBuildView.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowConnections.test.js
test/unit/studio/src/windowManagement/contentWindows/shared.js

feat: Update internalDiscovery endpoint url

---

studio/src/keyboardShortcuts/KeyboardShortcutManager.js
studio/src/keyboardShortcuts/ShorcutConditionValueSetter.js
studio/src/keyboardShortcuts/autoRegisterShortcutCommands.js
studio/src/keyboardShortcuts/autoRegisterShortcutConditions.js
studio/src/ui/NumericGui.js
test/unit/studio/src/keyboardShortcuts/KeyboardShortcutManager.test.js
test/unit/studio/src/ui/NumericGui.test.js

refactor: Use shortcut system for numeric guis

---

studio/src/assets/AssetManager.js
studio/src/preferences/autoRegisterPreferences.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.test.js

fix: Don't request write permission when opening a project

---

studio/src/projectSelector/ProjectManager.js

feat: Add opened projects to recent list when opened from the file picker

---

.vscode/settings.json
scripts/check.js
scripts/dev.js
src/components/builtIn/CameraComponent.js
studio/src/assets/AssetManager.js
studio/src/assets/ProjectAsset.js
studio/src/assets/projectAssetType/ProjectAssetType.js
studio/src/assets/projectAssetType/ProjectAssetTypeMaterialMap.js
studio/src/tasks/TaskManager.js
studio/src/ui/ArrayGui.js
studio/src/ui/ObjectGui.js
studio/src/ui/propertiesTreeView/PropertiesTreeViewEntry.js
studio/src/ui/propertiesTreeView/types.ts
test/e2e/shared/browser.js
test/unit/studio/shared/mockTreeView/PropertiesTreeViewEntry.js
test/unit/studio/shared/mockTreeView/castTreeView.js
test/unit/studio/src/assets/ProjectAsset/readWriteAssetData.test.js
test/unit/studio/src/assets/materialMapTypeSerializers/MaterialMapTypeSerializerWebGpu.test.js
test/unit/studio/src/misc/ServiceWorkerManager.test.js
test/unit/studio/src/tasks/TaskManager.test.js
test/unit/studio/src/ui/DroppableGui/shared.js

chore: Upgrade TypeScript

---

test/e2e/shared/browser.js
test/e2e/shared/runE2eTest.js
test/e2e/studio/src/assets/embeddedAssets.test.js
test/e2e/studio/src/assets/projectAssetType/ProjectAssetTypeWebGpuPipelineConfig.test.js
test/e2e/studio/src/projectSelector/projectSelector.test.js
test/e2e/studio/src/ui/DropDownGui/DropDownGui.test.js
test/e2e/studio/src/ui/PathGui/PathGui.test.js
test/e2e/studio/src/windowManagement/contentWindows/OutlinerContentWindow.test.js
test/e2e/studio/src/windowManagement/workspaces.test.js

test: Add timeout to e2e tests

---

scripts/DevServer.js

chore: Fix studio discovery not working in development

---

studio/src/assets/AssetManager.js
studio/src/preferences/preferencesLocation/FilePreferencesLocation.js
studio/src/preferences/preferencesLocation/PreferencesLocation.js
studio/src/projectSelector/ProjectManager.js
studio/src/projectSelector/ProjectSettingsManager.js
studio/src/util/fileSystems/StudioFileSystem.js
test/unit/studio/src/assets/AssetManager/internallyCreatedAssets.test.js
test/unit/studio/src/assets/AssetManager/misc.test.js
test/unit/studio/src/preferences/preferencesLocation/FilePreferencesLocation.test.js
test/unit/studio/src/projectSelector/ProjectManager.test.js

feat: Add project and version control preference locations

---

src/util/MultiKeyWeakMap.js
test/unit/shared/mockWeakRef.js
test/unit/src/util/MultiKeyWeakMap.test.js

feat: Support for string keys in MultiKeyWeakMap

---

scripts/DevServer.js

chore: Disable cache in development server

---

studio/src/projectSelector/ProjectSelector.js
studio/src/util/fileSystems/IndexedDbStudioFileSystem.js
test/unit/studio/src/projectSelector/ProjectSelector.test.js
test/unit/studio/src/projectSelector/shared.js
test/unit/studio/src/util/fileSystems/IndexedDbStudioFileSystem/misc.test.js

fix: Add a fallback for browsers that don't support indexedDB.databases()

---

studio/src/preferences/autoRegisterPreferences.js

feat: Change entityEditor.orbitLookDist default to 2.5

---

studio/builtInAssets/gizmos/billboard gizmo/Pipeline Config.json
studio/builtInAssets/gizmos/mesh gizmo/Pipeline Config.json

feat: Disable depth testing on gizmo meshes

---

studio/src/ui/popoverMenus/popoverMenus.css

fix: Use the correct text color for disabled context menus

---

src/util/gltf/applyMeshComponents.js
src/util/gltf/parseJsonData.js
studio/src/assets/projectAssetType/ProjectAssetTypeGltf.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/src/util/gltf/parseJsonData/assertAssetVersion.test.js
test/unit/studio/src/assets/projectAssetType/ProjectAssetTypeGltf.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.test.js

feat: Always start entity editors with an empty entity

---

src/assets/AssetLoader.js
src/assets/assetLoaderTypes/AssetLoaderType.js
src/assets/assetLoaderTypes/AssetLoaderTypeClusteredLightsConfig.js
src/assets/assetLoaderTypes/AssetLoaderTypeEntity.js
src/assets/assetLoaderTypes/AssetLoaderTypeGenericStructure.js
src/assets/assetLoaderTypes/AssetLoaderTypeMaterial.js
src/assets/assetLoaderTypes/AssetLoaderTypeMaterialMap.js
src/assets/assetLoaderTypes/AssetLoaderTypeMesh.js
src/assets/assetLoaderTypes/AssetLoaderTypeRenderOutputConfig.js
src/assets/assetLoaderTypes/AssetLoaderTypeSampler.js
src/assets/assetLoaderTypes/AssetLoaderTypeShaderSource.js
src/assets/assetLoaderTypes/AssetLoaderTypeVertexState.js
src/assets/assetLoaderTypes/AssetLoaderTypeWebGpuPipelineConfig.js
studio/src/assets/projectAssetType/ProjectAssetType.js
test/unit/shared/typeAssertions.js
test/unit/src/assets/AssetLoader.test.js
test/unit/src/assets/assetLoaderTypes/AssetLoaderTypeShaderSource.test.js
test/unit/studio/src/assets/ProjectAsset/getBundledAssetData.test.js
test/unit/studio/src/assets/projectAssetType/ProjectAssetTypeMaterialMap.test.js
test/unit/studio/src/assets/projectAssetType/shared.js

refactor: Add generics to AssetLoaderTypes

---

studio/builtInAssets/assetSettings.json
studio/devSocket/src/BuiltInAssetManager.js
test/unit/studio/devSocket/src/BuiltInAssetManager.test.js

chore: Better built in asset settings sorting

---

src/assets/AssetLoader.js
src/assets/EngineAssetsManager.js
src/gizmos/GizmoManager.js
src/rendering/renderers/webGpu/ClusterComputeManager.js
src/rendering/renderers/webGpu/WebGpuRenderer.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.js
test/unit/shared/typeAssertions.js
test/unit/src/assets/EngineAssetsManager/disabledUpdatesSupport.test.js
test/unit/src/assets/EngineAssetsManager/enabledUpdatesSupport.test.js
test/unit/src/assets/EngineAssetsManager/shared.js
test/unit/src/assets/EngineAssetsManager/types.test.js
test/unit/src/gizmos/shared.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor.test.js

refactor: Add assertion options support and types to EngineAssetsManager

---

src/gizmos/gizmos/iconGizmos/IconGizmo.js
test/unit/src/gizmos/gizmos/IconGizmo.test.js

fix: Set unusedComponentCount to icon gizmos position attribute

---

.github/codecov.yml

This reverts commit 7d29e662dd2adacb7624c83653d84816ced26243.

Revert "chore: Stricter code coverage enforcement"

---

studio/src/assets/projectAssetType/ProjectAssetTypeEntity.js
studio/src/ui/TreeView.js
studio/src/ui/treeView.css
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/ui/TreeView/afterEl.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

feat: Visually distinguish linked entity assets in the outliner

---

studio/src/windowManagement/SplitStudioWindow.js
studio/src/windowManagement/TabsStudioWindow.js
studio/src/windowManagement/WindowManager.js
studio/src/windowManagement/WorkspaceManager.js
test/unit/studio/shared/contextMenuHelpers.js
test/unit/studio/src/windowManagement/WindowManager.test.js
test/unit/studio/src/windowManagement/WorkspaceManager.test.js

fix: Save workspace when closing the last tab of a window

---

studio/src/ui/popoverMenus/PopoverManager.js
studio/src/ui/popoverMenus/PopoverToggleButton.js
studio/src/windowManagement/PreferencesPopover.js
studio/src/windowManagement/contentWindows/ContentWindow.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/EntryPointPopover.js
test/unit/studio/src/ui/popoverMenus/PopoverManager.test.js
test/unit/studio/src/ui/popoverMenus/PopoverToggleButton.test.js
test/unit/studio/src/windowManagement/PreferencesPopover.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindow/preferencesButton.test.js

refactor: Incorporate popover initialize methods inside their constructors

---

studio/src/assets/projectAssetType/ProjectAssetTypeEntity.js
test/unit/studio/src/assets/projectAssetType/ProjectAssetTypeEntity.test.js

fix: Make correct use of the recursion tracker when loading entity liveAssets

---

studio/src/windowManagement/TabsStudioWindow.js
studio/src/windowManagement/WorkspaceManager.js
test/unit/studio/src/windowManagement/WindowManager.test.js

fix: Use "user" trigger in workspace events when clicking tab buttons

---

studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

fix: Notify entity editors when renaming an entity from the outliner

---

src/gizmos/GizmoManager.js
src/gizmos/draggables/GizmoDraggable.js
src/gizmos/draggables/ScaleGizmoDraggable.js
src/gizmos/gizmos/ScaleGizmo.js
src/gizmos/mod.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/static/icons/entityEditor/scale.svg
test/unit/src/gizmos/draggables/AllGizmoDraggables.test.js
test/unit/src/gizmos/draggables/ScaleGizmoDraggable.test.js
test/unit/src/gizmos/gizmos/ScaleGizmo.test.js

feat: Add a scale gizmo to the entity editor

---

src/util/EventHandler.js
studio/src/assets/EntityAssetManager.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/assets/EntityAssetManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

feat: Update outliner when linked entity assets change

---

studio/src/preferences/autoRegisterPreferences.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/EntitySavingManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/shared.js
test/unit/studio/src/windowManagement/contentWindows/shared.js

feat: Add entityEditor.showGrid preference

---

src/core/Entity.js
studio/src/assets/EntityAssetManager.js
test/unit/src/core/Entity/clone.test.js
test/unit/studio/src/assets/EntityAssetManager.test.js

feat: Support nested entity assets in the EntityAssetManager

---

src/core/Entity.js
studio/src/propertiesWindowContent/PropertiesWindowContentEntity.js
studio/src/ui/TreeView.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/src/core/Entity/hierarchy.test.js
test/unit/studio/src/ui/TreeView/hierarchy.test.js
test/unit/studio/src/ui/TreeView/shared.js

fix: Make better use of new EntityAssetManager functionality in the outliner

---

studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/orbitAndEntityUuidPrefs.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/shared.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

feat: Use tracked entity assets as root in entity editors

---

studio/src/preferences/PreferencesManager.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/EntitySavingManager.js
test/unit/studio/src/preferences/PreferencesManager.test.js
test/unit/studio/src/projectSelector/ProjectManager.test.js
test/unit/studio/src/windowManagement/WindowManager.test.js

refactor: Make PreferencesManager.get contentwindow uuids required

---

importmap.json
src/core/Entity.js
studio/src/assets/EntityAssetManager.js
studio/src/assets/projectAssetType/ProjectAssetTypeEntity.js
studio/src/ui/TreeView.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
studio/src/windowManagement/contentWindows/ContentWindowProject.js
test/unit/studio/shared/treeViewUtil.js
test/unit/studio/src/assets/EntityAssetManager.test.js
test/unit/studio/src/assets/projectAssetType/ProjectAssetTypeEntity.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowProject.test.js

feat: Drag entities from the outliner to the project to create nested entity assets

---

importmap.json
studio/src/assets/EntityAssetManager.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/shared/contextMenuHelpers.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

fix: Improved updateEntity calls in the outliner

---

src/core/Entity.js
studio/src/assets/EntityAssetManager.js
test/unit/src/core/Entity/clone.test.js
test/unit/studio/src/assets/EntityAssetManager.test.js

fix: Update position on source entities as well

---

studio/src/assets/EntityAssetManager.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/assets/EntityAssetManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

feat: Also fire onTrackedEntityChange events on the entity that was edited

---

studio/src/assets/EntityAssetManager.js
studio/src/propertiesWindowContent/PropertiesWindowContentEntity.js
test/unit/studio/shared/createMockEntityAssetManager.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowConnections.test.js
test/unit/studio/src/windowManagement/contentWindows/shared.js
test/unit/studio/src/windowManagement/propertiesWindowContent/PropertiesWindowContentEntity.test.js
test/unit/studio/src/windowManagement/propertiesWindowContent/shared.js
test/unit/studio/src/windowManagement/shared.js

feat: Use new entity EntityAssetManager in the entity properties window

---

studio/src/propertiesWindowContent/PropertiesWindowContentEntity.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/EntitySavingManager.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js
test/unit/studio/src/windowManagement/propertiesWindowContent/PropertiesWindowContentEntity.test.js

refactor: Remove old notifyEntityChanged method

---

studio/src/assets/EntityAssetManager.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/EntitySavingManager.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/assets/EntityAssetManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/EntitySavingManager.test.js
test/unit/studio/src/windowManagement/propertiesWindowContent/PropertiesWindowContentEntity.test.js

feat: Autosave nested entity assets

---

studio/src/assets/EntityAssetManager.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/assets/EntityAssetManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/orbitAndEntityUuidPrefs.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/shared.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

feat: Allow dragging root entities from the outliner to the project window

---

src/rendering/renderers/webGpu/WebGpuRenderer.js

fix: Use world position for rendering lights

---

src/assets/assetLoaderTypes/AssetLoaderTypeEntity.js
src/core/Entity.js
studio/src/assets/projectAssetType/ProjectAssetTypeEntity.js
test/unit/src/core/Entity/transformations.test.js

feat: Support for editing localMatrix and worldMatrix in place

---

src/rendering/renderers/webGpu/WebGpuRenderer.js
src/rendering/renderers/webGpu/WebGpuRendererError.js

feat: Throw more clear errors when webgpu is not supported

---

studio/src/Studio.js
studio/src/styles/dummyStylesModule.js
studio/src/styles/readme.md
studio/src/styles/shadowStyles.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.css
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/rendererErrorMessage.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/shared.js

feat: Show an error message when initializing the renderer fails

---

studio/src/Studio.js
studio/src/preferences/preferencesLocation/FilePreferencesLocation.js
studio/src/preferences/preferencesLocation/PreferencesLocation.js
studio/src/preferences/preferencesLocation/WorkspacePreferencesLocation.js
studio/src/projectSelector/ProjectManager.js
studio/src/windowManagement/WindowManager.js
studio/src/windowManagement/WorkspaceManager.js
test/unit/studio/src/projectSelector/ProjectManager.test.js
test/unit/studio/src/windowManagement/WindowManager.test.js
test/unit/studio/src/windowManagement/WorkspaceManager.test.js

feat: Add a workspace preferences location

---

studio/src/preferences/preferencesLocation/ContentWindowPreferencesLocation.js
studio/src/windowManagement/WindowManager.js
studio/src/windowManagement/contentWindows/ContentWindow.js
test/unit/studio/src/preferences/PreferencesManager.test.js
test/unit/studio/src/windowManagement/PreferencesPopover.test.js
test/unit/studio/src/windowManagement/WindowManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/shared.js

feat: Add contentwindow-workspace preference location

---

.github/workflows/deploy-pr.yml

First step towards fixing #138

chore: Remove old PR deployments when a new one is created

---

studio/src/preferences/PreferencesManager.js
studio/src/preferences/autoRegisterPreferences.js
studio/src/ui/propertiesTreeView/PropertiesTreeViewEntry.js
studio/src/windowManagement/PreferencesPopover.js
test/unit/studio/shared/treeViewUtil.js
test/unit/studio/shared/treeViewUtil.test.js
test/unit/studio/src/preferences/PreferencesManager.test.js
test/unit/studio/src/windowManagement/PreferencesPopover.test.js

feat: Add allowedLocations option to preferences

---

studio/src/Studio.js
studio/src/network/studioConnections/readme.md
studio/src/preferences/PreferencesManager.js
studio/src/preferences/autoRegisterPreferences.js
studio/src/projectSelector/ProjectManager.js
studio/src/windowManagement/contentWindows/ContentWindowConnections.js
test/unit/studio/src/preferences/PreferencesManager.test.js
test/unit/studio/src/projectSelector/ProjectManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowConnections.test.js

feat: Move allow connections preferences to new preferences manager

---

studio/src/preferences/autoRegisterPreferences.js
studio/src/ui/ButtonSelectorGui.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/EntryPointPopover.js
test/unit/studio/src/ui/ButtonSelectorGui.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowBuildView/EntryPointPopover.test.js

feat: Move buildview preferences to new PreferencesManager

---

studio/src/preferences/PreferencesManager.js
studio/src/ui/propertiesTreeView/PropertiesTreeViewEntry.js
studio/src/windowManagement/PreferencesPopover.js
test/unit/studio/shared/treeViewUtil.js
test/unit/studio/shared/treeViewUtil.test.js
test/unit/studio/src/preferences/PreferencesManager.test.js
test/unit/studio/src/windowManagement/PreferencesPopover.test.js

feat: Add tooltips with info to preferences

---

src/inspector/InspectorManager.js
src/inspector/InternalDiscoveryManager.js
studio/src/network/studioConnections/StudioConnectionsManager.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryWorkerMain.js
studio/src/network/studioConnections/internalDiscovery/readme.md
studio/src/network/studioConnections/readme.md
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
test/unit/src/inspector/InternalDiscoveryManager.test.js
test/unit/studio/src/network/studioConnections/MockInternalDiscoveryManager.js
test/unit/studio/src/network/studioConnections/StudioConnectionsManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.test.js

Fixes #747
Fixes #748
Fixes #750

feat: Make inspectors automatically connect to the parent studio instance

---

src/util/TypedMessenger.js
studio/src/tasks/task/TaskBuildApplication.js
studio/src/tasks/task/TaskBundleAssets.js
studio/src/tasks/task/TaskBundleScripts.js
studio/src/tasks/workers/buildApplication/mod.js
studio/src/tasks/workers/bundleAssets/mod.js
studio/src/tasks/workers/bundleScripts/mod.js
test/unit/src/util/TypedMessenger/TypedMessenger.test.js
test/unit/src/util/TypedMessenger/shared/workerWithInitialize.js

feat: Separate TypedMessenger initialize into multiple methods

---

src/components/builtIn/CameraComponent.js
src/components/builtIn/LightComponent.js
src/components/builtIn/MeshComponent.js

refactor: Use satisfies for component gui structures

---

src/util/WeakValueMap.js
src/util/mod.js
test/unit/src/util/WeakValueMap.test.js

I wrote this accidentally, could come in handy one day

feat(util): Add WeakValueMap

---

src/util/TypedMessenger.js
test/unit/src/util/TypedMessenger/TypedMessenger.test.js

feat(TypedMessenger): Add configureSendOptions()

---

src/math/Mat4.js
test/unit/src/math/Mat4.test.js

feat(math): Make some Mat4 methods return this

---

src/inspector/InternalDiscoveryManager.js
src/util/TypedMessenger/TypedMessenger.js
src/util/TypedMessenger/errorSerialization.js
src/util/mod.js
studio/src/misc/ServiceWorkerManager.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryIframeMain.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryWorkerMain.js
studio/src/tasks/task/TaskBuildApplication.js
studio/src/tasks/task/TaskBundleAssets.js
studio/src/tasks/task/TaskBundleScripts.js
studio/src/tasks/workers/buildApplication/mod.js
studio/src/tasks/workers/bundleAssets/mod.js
studio/src/tasks/workers/bundleScripts/mod.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
studio/sw.js
test/unit/src/inspector/InternalDiscoveryManager.test.js
test/unit/src/util/TypedMessenger/TypedMessenger/TypedMessenger.test.js
test/unit/src/util/TypedMessenger/TypedMessenger/initializeWebSocket.test.js
test/unit/src/util/TypedMessenger/TypedMessenger/shared/workerWithInitialize.js
test/unit/src/util/TypedMessenger/errorSerialization.test.js
test/unit/studio/src/misc/ServiceWorkerManager.test.js
test/unit/studio/src/tasks/TaskManager.test.js
test/unit/studio/src/tasks/shared/basicWorker.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.test.js

feat(util): Add TypedMessenger error serialization

---

studio/index.html

Second attempt, not sure why #828 didn't work...

feat(studio connections): Add new origin trail for disabling third party storage partitioning

---

src/math/Mat4.js
src/rendering/CustomMaterialData.js
src/rendering/Material.js
src/rendering/MaterialMap.js
src/rendering/mod.js
src/rendering/renderers/webGpu/CachedCameraData.js
src/rendering/renderers/webGpu/CachedMaterialData.js
src/rendering/renderers/webGpu/WebGpuRenderer.js
src/rendering/renderers/webGpu/bufferHelper/WebGpuChunkedBuffer.js
src/rendering/renderers/webGpu/bufferHelper/WebGpuChunkedBufferChunk.js
src/rendering/renderers/webGpu/bufferHelper/WebGpuChunkedBufferGroup.js
src/util/wgslParsing.js
studio/src/assets/materialMapTypeSerializers/MaterialMapTypeSerializerWebGpu.js
studio/src/propertiesAssetContent/PropertiesAssetContentMaterial.js
studio/src/propertiesAssetContent/propertiesAssetContentMaterialMap/MaterialMapListUi.js
test/unit/src/rendering/CustomMaterialData.test.js
test/unit/src/rendering/Material.test.js
test/unit/src/rendering/MaterialMap.test.js
test/unit/src/rendering/renderers/webGpu/CachedMaterialData.test.js
test/unit/src/rendering/renderers/webGpu/WebGpuRenderer.test.js
test/unit/src/rendering/renderers/webGpu/bufferHelper/WebGpuChunkedBuffer.test.js
test/unit/src/rendering/renderers/webGpu/bufferHelper/WebGpuChunkedBufferGroup.test.js
test/unit/src/rendering/renderers/webGpu/shared/webGpuConstants.js
test/unit/src/util/wgslParsing/parseMaterialUniforms.test.js
test/unit/studio/src/assets/materialMapTypeSerializers/MaterialMapTypeSerializerWebGpu.test.js
test/unit/studio/src/propertiesAssetContent/PropertiesAssetContentMaterial.test.js
test/unit/studio/src/propertiesAssetContent/propertiesAssetContentMaterialMap/MaterialMapListUi.test.js

feat(WebGPU): Support for custom material property types

---

src/math/Mat4.js
src/util/OrbitControls.js
studio/src/preferences/autoRegisterPreferences.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
test/unit/src/components/builtIn/CameraComponent.test.js
test/unit/src/gizmos/draggables/RotateAxisGizmoDraggable.test.js
test/unit/src/gizmos/draggables/ScaleGizmoDraggable.test.js
test/unit/src/gizmos/draggables/TranslateAxisGizmoDraggable.test.js
test/unit/src/gizmos/draggables/TranslateGizmoDraggable.test.js
test/unit/src/gizmos/shared.js
test/unit/src/math/Mat4.test.js
test/unit/src/util/OrbitControls.test.js
test/unit/src/util/cameraUtil.test.js

feat: Flip depth axis on projection matrices

---

src/inspector/InspectorManager.js
src/network/studioConnections/DiscoveryManager.js
src/network/studioConnections/discoveryMethods/DiscoveryMethod.js
src/network/studioConnections/discoveryMethods/InternalDiscoveryMethod.js
src/network/studioConnections/discoveryMethods/WebRtcDiscoveryMethod.js
src/network/studioConnections/messageHandlers/InternalMessageHandler.js
src/network/studioConnections/messageHandlers/MessageHandler.js
studio/src/network/studioConnections/StudioConnectionsManager.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryWorkerMain.js
studio/src/network/studioConnections/readme.md
studio/src/ui/TreeView.js
studio/src/windowManagement/contentWindows/ContentWindowConnections.js
test/e2e/studio/src/inspector/InspectorAssetBundle.test.js
test/unit/src/inspector/InspectorManager/InspectorManager.test.js
test/unit/src/network/studioConnections/DiscoveryManager.test.js
test/unit/src/network/studioConnections/discoveryMethods/DiscoveryMethod.test.js
test/unit/src/network/studioConnections/discoveryMethods/InternalDiscoveryMethod.test.js
test/unit/src/network/studioConnections/discoveryMethods/shared/ExtendedDiscoveryMethod.js
test/unit/studio/src/network/studioConnections/StudioConnectionsManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowConnections.test.js

feat: Show permission prompt when receiving studio connection

---

src/network/studioConnections/DiscoveryManager.js
src/network/studioConnections/ParentStudioCommunicator.js
src/network/studioConnections/discoveryMethods/DiscoveryMethod.js
src/network/studioConnections/discoveryMethods/InternalDiscoveryMethod.js
src/network/studioConnections/discoveryMethods/WebRtcDiscoveryMethod.js
src/network/studioConnections/messageHandlers/InternalMessageHandler.js
src/network/studioConnections/messageHandlers/MessageHandler.js
studio/src/network/studioConnections/StudioConnectionsManager.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryWorkerMain.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
test/e2e/studio/src/inspector/InspectorAssetBundle.test.js
test/unit/src/inspector/InspectorManager/InspectorManager.test.js
test/unit/src/network/studioConnections/DiscoveryManager.test.js
test/unit/src/network/studioConnections/discoveryMethods/DiscoveryMethod.test.js
test/unit/src/network/studioConnections/discoveryMethods/InternalDiscoveryMethod.test.js
test/unit/src/network/studioConnections/discoveryMethods/WebRtcDiscoveryMethod/WebRtcDiscoveryMethod.test.js
test/unit/src/network/studioConnections/discoveryMethods/shared/ExtendedDiscoveryMethod.js
test/unit/studio/src/network/studioConnections/StudioConnectionsManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.test.js

feat(studio connections): Auto connect inspector connections inside the build view iframe

---

src/inspector/InspectorManager.js
src/network/studioConnections/DiscoveryManager.js
src/network/studioConnections/StudioConnection.js
src/network/studioConnections/messageHandlers/InternalMessageHandler.js
src/network/studioConnections/messageHandlers/MessageHandler.js
src/util/TypedMessenger/TypedMessenger.js
studio/src/network/studioConnections/StudioConnectionsManager.js
studio/src/network/studioConnections/handlers.js
studio/src/network/studioConnections/responseHandlers/fileSystem.js
studio/src/util/fileSystems/MemoryFileSystemWritableFileStream.js
test/unit/src/inspector/InspectorManager/shared.js
test/unit/src/network/studioConnections/DiscoveryManager.test.js
test/unit/src/network/studioConnections/StudioConnection.test.js
test/unit/src/network/studioConnections/discoveryMethods/InternalDiscoveryMethod.test.js
test/unit/src/network/studioConnections/shared.js
test/unit/studio/src/util/fileSystems/all/shared.js
test/unit/studio/src/util/fileSystems/all/tests/createDir.test.js
test/unit/studio/src/util/fileSystems/all/tests/delete.test.js
test/unit/studio/src/util/fileSystems/all/tests/isFile.test.js
test/unit/studio/src/util/fileSystems/all/tests/move.test.js
test/unit/studio/src/util/fileSystems/all/tests/readDir.test.js
test/unit/studio/src/util/fileSystems/all/tests/readFile.test.js
test/unit/studio/src/util/fileSystems/all/tests/rootName.test.js
test/unit/studio/src/util/fileSystems/all/tests/writeFile.test.js
test/unit/studio/src/util/fileSystems/all/tests/writeFileStream.test.js

feat(studio connections): Support for binary serialization of messages

---

src/util/OrbitControls.js
studio/src/ui/NumericGui.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js

fix: Make some event listeners explicitly passive

---

src/rendering/renderers/webGpu/CachedMeshData.js
test/unit/src/rendering/renderers/webGpu/CachedMeshData.test.js

fix(WebGPU): Pad index buffers to make their size a multiple of 4

---

src/assets/assetLoaderTypes/AssetLoaderTypeMaterialMap.js
src/rendering/Material.js
src/rendering/MaterialMap.js
src/rendering/renderers/webGpu/WebGpuRenderer.js
src/util/meshShapeGeneration/cube.js
src/util/meshShapeGeneration/uvSphere.js
studio/src/assets/materialMapTypeSerializers/MaterialMapTypeSerializer.js
studio/src/assets/materialMapTypeSerializers/MaterialMapTypeSerializerWebGpu.js
studio/src/assets/projectAssetType/ProjectAssetTypeMaterialMap.js
studio/src/propertiesAssetContent/PropertiesAssetContentMaterial.js
studio/src/propertiesAssetContent/propertiesAssetContentMaterialMap/MaterialMapListUi.js
test/unit/src/rendering/Material.test.js
test/unit/src/rendering/MaterialMap.test.js
test/unit/src/util/meshShapeGeneration/cube.test.js
test/unit/src/util/meshShapeGeneration/uvSphere.test.js
test/unit/studio/src/assets/MaterialMapTypeSerializerManager.test.js
test/unit/studio/src/assets/materialMapTypeSerializers/MaterialMapTypeSerializerWebGpu.test.js
test/unit/studio/src/assets/projectAssetType/ProjectAssetTypeMaterialMap.test.js
test/unit/studio/src/assets/projectAssetType/shared.js
test/unit/studio/src/propertiesAssetContent/PropertiesAssetContentMaterial.test.js
test/unit/studio/src/propertiesAssetContent/propertiesAssetContentMaterialMap/MaterialMapListUi.test.js

feat(WebGPU,Materials): Add backface culling

---

src/util/gltf/getMaterial.js
src/util/gltf/gltfParsing.js
src/util/gltf/parseJsonData.js
test/unit/src/util/gltf/getMaterial.test.js

feat(gltf): Apply cullmode and add material hook

---

studio/src/network/studioConnections/StudioConnectionsManager.js
studio/src/network/studioConnections/handlers.js
studio/src/network/studioConnections/responseHandlers/fileSystem.js
studio/src/projectSelector/ProjectManager.js
test/unit/studio/src/network/studioConnections/StudioConnectionsManager.test.js
test/unit/studio/src/util/fileSystems/all/shared.js
test/unit/studio/src/util/fileSystems/all/tests/createDir.test.js
test/unit/studio/src/util/fileSystems/all/tests/delete.test.js
test/unit/studio/src/util/fileSystems/all/tests/writeFile.test.js

fix(File System): Make change events work on remote file systems

---

studio/src/network/studioConnections/responseHandlers/fileSystem.js
studio/src/util/fileSystems/FsaStudioFileSystem.js
studio/src/util/fileSystems/IndexedDbStudioFileSystem.js
studio/src/util/fileSystems/MemoryStudioFileSystem.js
studio/src/util/fileSystems/RemoteStudioFileSystem.js
test/unit/studio/src/util/fileSystems/FsaStudioFileSystem/shared.js
test/unit/studio/src/util/fileSystems/all/tests/createDir.test.js
test/unit/studio/src/util/fileSystems/all/tests/delete.test.js
test/unit/studio/src/util/fileSystems/all/tests/move.test.js
test/unit/studio/src/util/fileSystems/all/tests/readDir.test.js
test/unit/studio/src/util/fileSystems/all/tests/readFile.test.js
test/unit/studio/src/util/fileSystems/all/tests/writeFile.test.js
test/unit/studio/src/util/fileSystems/all/tests/writeFileStream.test.js

- This changes the error messages from all different file system types to be pretty much the same.
- Implement `delete()` functionality on remote file systems
- Implemented `move()` functionality on remote file systems
- Fixed some minor issues and enabled their tests

feat(File System): Fix some failing tests

---

importmap.json
scripts/DevServer.js
scripts/buildStudio.js
studio/src/main.js
studio/src/misc/ServiceWorkerManager.js
studio/src/projectSelector/ProjectSelector.js
studio/src/projectSelector/projectSelector.css
studio/src/studioDefines.js
studio/src/styles/studioStyles.js
studio/src/ui/spinner.css
studio/src/ui/spinner.js
studio/src/windowManagement/TabsStudioWindow.js
studio/src/windowManagement/contentWindows/ContentWindow.js
studio/src/windowManagement/contentWindows/ContentWindowAbout.css
studio/src/windowManagement/contentWindows/ContentWindowAbout.js
studio/static/icons/circleCheck.svg
studio/sw.js
test/unit/studio/src/misc/ServiceWorkerManager.test.js
test/unit/studio/src/projectSelector/ProjectSelector.test.js
test/unit/studio/src/projectSelector/shared.js
test/unit/studio/src/ui/shared.js
test/unit/studio/src/windowManagement/WindowManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowAbout.test.js

feat: Add offline support

---

studio/index.html
studio/static/manifest.json
studio/static/renda-circle.svg

feat: Add web app manifest

---

.github/workflows/ci.yml

chore: Add codecov upload token

---

src/core/Mesh.js
src/core/MeshAttributeBuffer.js
test/unit/src/core/Mesh/Mesh.test.js
test/unit/src/core/Mesh/clone.test.js
test/unit/src/core/Mesh/shared.js
test/unit/src/core/MeshAttributeBuffer/MeshAttributeBuffer.test.js
test/unit/src/core/MeshAttributeBuffer/clone.test.js
test/unit/src/core/MeshAttributeBuffer/shared.js

feat(core): Add Mesh.clone()

---

src/core/Entity.js
test/unit/src/core/Entity/transformations.test.js

fix(Entities): Invalidate matrix cache when setting a world matrix

---

studio/src/main.js

fix: Don't bundle e2e test functions in release builds

---

src/core/Mesh.js
test/unit/src/core/Mesh/Mesh.test.js
test/unit/src/core/Mesh/shared.js

feat(Mesh): Add Vec4 type to setVertexData

---

src/assets/assetLoaderTypes/AssetLoaderTypeShaderSource.js
test/unit/src/assets/assetLoaderTypes/AssetLoaderTypeShaderSource.test.js
test/unit/src/assets/shared.js

feat(AssetLoading): Throw when loading a shader asset without a shaderbuilder

---

src/core/Mesh.js
src/core/MeshAttributeBuffer.js
test/unit/src/core/Mesh/Mesh.test.js
test/unit/src/core/MeshAttributeBuffer/MeshAttributeBuffer.test.js
test/unit/src/core/MeshAttributeBuffer/clone.test.js

refactor(Mesh): Make some properties and methods private

---

scripts/buildEngine.js
scripts/buildJsrPackage.js
scripts/buildNpmPackage.js
scripts/buildStudio.js
scripts/shared/overrideDefinesPlugin.js
scripts/shared/verifyVersion.js
src/engineDefines.js
src/mod.js
studio/src/projectSelector/ProjectSelector.js
studio/src/studioDefines.js
studio/src/windowManagement/contentWindows/ContentWindowAbout.js

- Include minified builds
- Verify version string when building npm or jsr package
- Disable studio defines in builds
- Include renda version in package

feat: Several package publishing improvements

---

src/core/Mesh.js
src/core/MeshAttributeBuffer.js
test/unit/src/core/MeshAttributeBuffer/MeshAttributeBuffer.test.js
test/unit/src/core/MeshAttributeBuffer/clone.test.js
test/unit/src/core/MeshAttributeBuffer/shared.js

refactor(Mesh): Don't store reference to the mesh in attribute buffers

---

src/core/Entity.js
studio/src/misc/SelectionManager.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
test/unit/src/core/Entity/transformations.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/transformationGizmos.test.js

fix(EntityEditor): Use cloned world matrices

---

studio/src/propertiesWindowContent/PropertiesWindowContentEntity.js

feat: Remove entity editing mode UI

---

.github/workflows/ci.yml

This might be required for #925 to get merged

chore: Add read permission to unit tests workflow

---

.github/workflows/ci.yml

chore: Use Codecov secret

---

src/util/OrbitControls.js
src/util/ScrollHardwareDetector.js
src/util/mod.js
studio/src/Studio.js
studio/src/preferences/PreferencesManager.js
studio/src/preferences/autoRegisterPreferences.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
test/unit/shared/typeAssertions.js
test/unit/src/util/OrbitControls.test.js
test/unit/src/util/ScrollHardwareDetector.test.js
test/unit/studio/src/preferences/PreferencesManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/orbitAndEntityUuidPrefs.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/shared.js

feat(EntityEditor): Preference for scrollwheel behavior

---

src/math/Mat4.js
src/math/Quat.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
test/unit/src/math/Mat4.test.js
test/unit/src/math/Quat.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/transformationGizmos.test.js

feat(math)!: Move `Quat.toMat4()` to `Mat4.createRotation()`

---

scripts/test.js
test/readme.md

- Use deno coverage for generating html reports
- Fix no tests getting run when no filter is provided

test: Test script improvements

---

src/assets/assetBundles/DownloadableAssetBundle.js
src/util/BinaryComposer.js
src/util/BinaryDecomposer.js
studio/src/misc/thirdPartyLicenses/draco.js
studio/src/misc/thirdPartyLicenses/mod.js
studio/src/misc/thirdPartyLicenses/rollup.js
studio/src/tasks/workers/bundleAssets/bundle.js
studio/src/tasks/workers/bundleAssets/mod.js
studio/src/windowManagement/contentWindows/ContentWindowAbout.js
test/unit/src/assets/assetBundles/DownloadableAssetBundle.test.js
test/unit/studio/src/tasks/task/TaskBundleAssets.test.js
test/unit/studio/src/util/BinaryComposerAndDecomposer.test.js

feat: Include bundle size and other metadata in the asset bundle header
