editor/src/util/fileSystems/FsaEditorFileSystem.js
test/unit/editor/src/util/fileSystems/FsaEditorFileSystem/misc.test.js
test/unit/editor/src/util/fileSystems/IndexedDbEditorFileSystem/misc.test.js
test/unit/editor/src/util/fileSystems/MemoryEditorFileSystem/isDir.test.js
test/unit/editor/src/util/fileSystems/MemoryEditorFileSystem/isFile.test.js

fix(fsa filesystem): Don't throw when calling isFile with non existent parent dir

---

editor/src/propertiesAssetContent/AssetBundlePropertiesAssetContent.js
editor/src/ui/DroppableGui.js
editor/src/windowManagement/contentWindows/DefaultAssetLinksContentWindow.js
importmap.json
test/unit/editor/src/ui/DroppableGui/dragEvents.test.js
test/unit/editor/src/ui/DroppableGui/shared.js

The `supportedAssetTypes` option of droppable guis initially required `ProjectAsset` to be provided in order to constrain droppable guis to only assets. But dropping anything other than assets wasn't actually working at all.
This change removes this requirement and instead dropping is always only constrained to assets.
Lack of typing also caused an error to be thrown in cases where the `supportedAssetTypes` option was an empty array. This should be fixed as well.
Fixes #32

fix(droppablegui): Fix error when dropping on a gui which supports all asset types

---

.github/workflows/ci.yml

fix: Cache puppeteer download in CI

---

editor/dist/internalDiscovery/index.html
editor/scripts/build.js
src/Inspector/InternalDiscoveryManager.js

There's still some errors in release builds that I'll fix later
Fixes #52

fix: Use the correct casing for internal discovery paths

---

editor/src/projectSelector/ProjectManager.js
test/e2e/editor/shared/waitSeconds.js
test/e2e/editor/src/projectSelector/projectSelector.test.js

fix: Don't save contentWindowPersistentData when its empty

---

.github/workflows/build.yml
.github/workflows/deploy-canary.yml
.github/workflows/deploy-pr.yml

- Use the PR id as task id in order to invalidate old deployments on the same PR.
- Split build job into a separate workflow so that PRs get deployed sooner.

chore: Deployment improvements

---

editor/src/assets/projectAssetType/ProjectAssetTypeTask.js
editor/src/propertiesAssetContent/PropertiesAssetContentTask.js
editor/src/tasks/TaskManager.js
editor/src/tasks/environmentVariables.js
editor/src/tasks/task/Task.js
test/unit/editor/src/assets/shared/createMockProjectAsset.js
test/unit/editor/src/propertiesAssetContent/TaskPropertiesAssetContent.test.js
test/unit/editor/src/tasks/TaskManager.test.js
test/unit/editor/src/tasks/environmentVariables.test.js

This adds ui for modifying task environment variables and applies the environment variables to the task config.
Using environment variables for config properties other than strings is not supported yet. Though you might be able to manually edit the contents of task assets and replaced for instance boolean with a string that contains an environment variable.
Though these strings are not automatically replaced with the correct type. So tasks expecting a boolean might misinterpret a string containing `"false"` as a truthy value.
Fixes #62

feat(tasks): Add support for task environment variables

---

src/util/IndexedDbUtil.js
test/unit/editor/shared/FakeIndexedDbUtil.js

We were opening a new connection for every db request. This change makes it open only a single one and reuse that for every transaction.
When the connection gets garbage collected browsers should automatically close it as far as I can tell.
This change also ensures that the connection is closed when a database is deleted.
Fixes #22

fix: Use a single connection for IndexedDbUtil

---

editor/src/ui/TreeView.js
editor/src/windowManagement/contentWindows/ContentWindowBuiltInAssets.js
editor/src/windowManagement/contentWindows/ContentWindowOutliner.js
editor/src/windowManagement/contentWindows/ContentWindowProject.js

Calling focus() on an element seems to prevent dragstart events. So this change ensures treeviews are only focused when they don't have focus yet. Dragging an element also causes that element to get focus, so calling focus again isn't necessary.
However, this focus event causes the current selection to change, and as a result the properties window content is changed. To prevent this, we revert the focus to the previous element the moment a treeview is dragged. This causes a brief flicker while the focus is changed back and forth. Unfortunately there's little that can be done about this in regards to :focus-within css selectors. But the flickering of the content of the properties window could potentially be fixed in a follow up PR.
Fixes #133

feat: Don't change selection when dragging assets

---

editor/devSocket/src/BuiltInAssetManager.js
editor/src/assets/AssetManager.js
editor/src/assets/BuiltInAssetManager.js
editor/src/assets/ProjectAsset.js
editor/src/componentGizmos/gizmos/ComponentGizmosCamera.js
editor/src/network/DevSocketManager.js
editor/src/projectSelector/ProjectManager.js
editor/src/projectSelector/ProjectSettingsManager.js
editor/src/propertiesAssetContent/PropertiesAssetContentMaterial.js
editor/src/util/fileSystems/FsaEditorFileSystem.js
src/assets/AssetBundle.js
src/util/SingleInstancePromise.js
test/unit/shared/asserts.js
test/unit/shared/asserts.test.js
test/unit/src/util/SingleInstancePromise.js

fix: Don't make writeAssetData fill up the queue when calling frequently

---

src/core/Entity.js
test/unit/src/core/Entity/transformations.test.js

fix(core): Don't adjust local matrix on children when changing parent transformation

---

.github/workflows/deploy-canary.yml
.github/workflows/deploy-pr.yml

Because of https://github.com/actions/github-script/issues/286, deployments were failing. We'll downgrade for now until a fix is available.

chore: Downgrade actions/github-script

---

editor/src/assets/ProjectAssetTypeManager.js
editor/src/assets/projectAssetType/ProjectAssetTypeEntity.js
editor/src/misc/ServiceWorkerManager.js
editor/src/tasks/task/TaskGenerateServices.js
editor/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
editor/sw.js
jsconfig.json
src/util/TypedMessenger.js
test/unit/editor/src/assets/ProjectAssetTypeManager.test.js
test/unit/editor/src/assets/projectAssetType/ProjectAssetTypeEntity.test.js
test/unit/editor/src/tasks/task/TaskGenerateServices.test.js

- A lot of messaging logic with the service worker has been refactored to use TypedMessenger.
- Some of the dynamic url paths have been changed.
- A new url has been added for fetching a generated services script.
- An option has been added to the generate services task to include all code regardless of the entry points and used assets.
- Added some extra jsdoc documentation to TypedMessenger.
Fixes #166

feat: Generate services script for applications without building

---

editor/scripts/build.js
editor/src/network/editorConnections/EditorConnectionsManager.js
editor/src/network/editorConnections/internalDiscovery/internalDiscoveryMain.js
editor/src/network/editorConnections/internalDiscovery/internalDiscoveryWorkerMain.js
editor/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
src/Inspector/InspectorManager.js
src/Inspector/InternalDiscoveryManager.js
src/util/TypedMessenger.js
test/unit/src/inspector/InternalDiscoveryManager.test.js

- updated the build file to include a hash in the main entry points of scripts
- make InternalDiscoveryManager communicate with parent window in order to get the discovery iframe url
Fixes #268
Fixes #300

Make internal discovery work in production builds and remove facade chunks.

---

studio/src/ui/treeView.css

fix: Don't show focus ring around treeviews when navigating using the arrow keys

---

src/util/TypedMessenger.js
test/unit/src/util/TypedMessenger/TypedMessenger.test.js

feat: Add error serialization hooks to TypedMessenger

---

src/util/MultiKeyWeakMap.js
test/unit/src/util/MultiKeyWeakMap.test.js

Partially reverts #496
Using WeakRefs causes the values to get garbage collected even though the references to the keys are still being held.
This is not how WeakMaps are supposed to work.
This change makes it so that values that use strings as keys are never garbage collected at all. This should be fine as long as there are not too many/too big keys, and if the keys contain at least a single garbage collectable object in the array.

feat: Don't use WeakRefs for MultiKeyWeakMap string keys

---

.vscode/settings.json
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/EntryPointPopover.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.test.js

Fixes #444
This PR refactors the `EntryPointManager` class to a subclass of `Popover`.
This PR also fixes a small issue where the curtain would not appear, leading to some potential UI issues, and moves one test case to a path that better mirrors the existing `studio/` file structure.

Rewrite EntryPointManager as Popover subclass

---

test/e2e/studio/src/assets/embeddedAssets.test.js

We'll disable this test for now until a fix for #520 is available.

test: Disable flaky embedded assets e2e test

---

test/e2e/shared/browser.js
test/readme.md
test/shared/testArgs.js

- Adds `-h`/`--headless` and removes `--no-headless`. This flag toggles the default behaviour rather than just disabling headless mode. Allowing you to run in headless mode even though `--inspect` is used.
- Adds some documentation about permission issues on Linux
- Makes sure the page from the default context is hidden when headless is disabled. This page is always empty and only sits in the way.

test: Various improvements for running e2e tests locally

---

src/util/SingleInstancePromise.js
test/unit/src/util/SingleInstancePromise.test.js

Fixes #529
Previously `waitForFinishIfRunning` would resolve as soon as the first run was done. But more often than not when this function is used, you want it to resolve after *all* runs are done.
At the moment it seems like there are no cases where you'd want the old behaviour. If we ever need this again in the future we can either add a new method or add a parameter to this method.

feat: Don't resolve SingleInstancePromise.waitForFinishIfRunning when the queue is not empty

---

studio/src/windowManagement/StudioWindow.js
studio/src/windowManagement/WindowManager.js
studio/src/windowManagement/contentWindows/ContentWindow.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js

fix: Don't change focus to outliner treeview unless the content window element has been clicked

---

studio/src/windowManagement/SplitStudioWindow.js
studio/src/windowManagement/StudioWindow.js
studio/src/windowManagement/TabsStudioWindow.js
studio/src/windowManagement/WindowManager.js
studio/src/windowManagement/contentWindows/ContentWindow.js

- Instead of windows registering callbacks on children, events now automatically propagate up to the root and only fire the event there.
- events contain a `trigger` property, indicating what caused the update.

refactor: Workspace update event improvements

---

studio/src/projectSelector/ProjectManager.js
studio/src/windowManagement/contentWindows/ContentWindowDefaultAssetLinks.js
test/unit/studio/shared/createMockAssetManager.js
test/unit/studio/shared/runWithMockStudio.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowDefaultAssetLinks.test.js
test/unit/studio/src/windowManagement/contentWindows/shared.js

fix: Make handleGuiValueChange use the correct scope in the default asset links window

---

test/e2e/shared/browser.js
test/e2e/shared/e2eTestRunner.js

We used to download chromium within the first test that ran it. But something changed and chromium now takes longer to download or install, causing the first test to timeout and install a half version of chrome.
This change downloads chromium in advance before running any tests.

test: Download chromium before running any tests

---

studio/src/preferences/PreferencesManager.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/EntitySavingManager.js
test/unit/studio/src/preferences/PreferencesManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/EntitySavingManager.test.js

This change removes some functionality that allowed us to listen for changes without a specific content window uuid.
This was never used anywhere and wasn't actually working. A fix would have been difficult to add, because many different types of callbacks would have needed to be stored.
A new `onChangeAny` method has been added to listen for *all* events. Furthermore, some content window events weren't always firing, this has been fixed.
Fixes #675
Fixes #673

fix: Fire preference events more accurately

---

studio/src/assets/EntityAssetManager.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
studio/src/windowManagement/contentWindows/ContentWindowOutliner.js
test/unit/studio/src/assets/EntityAssetManager.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

This doesn't cover all cases, but should be a good starting point:
- Changing entity transformation when dragging using gizmos
- Creating new child entities in the outliner
- Renaming entities in the outliner
- Deleting entities from the outliner

feat: Fire entity change events when modifying entities

---

studio/builtInAssets/assetSettings.json
studio/builtInAssets/buildSupport/basicEntryPoint.js
studio/src/assets/AssetManager.js
studio/src/preferences/autoRegisterPreferences.js
studio/src/tasks/task/TaskBundleScripts.js
studio/src/ui/ButtonGroup.js
studio/src/ui/ButtonSelectorGui.js
studio/src/ui/propertiesTreeView/PropertiesTreeViewEntry.js
studio/src/ui/propertiesTreeView/types.ts
studio/src/windowManagement/contentWindows/ContentWindow.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/EntryPointPopover.js
studio/src/windowManagement/contentWindows/ContentWindowConnections.js
studio/src/windowManagement/contentWindows/ContentWindowEntityEditor/ContentWindowEntityEditor.js
test/unit/studio/src/assets/AssetManager/misc.test.js
test/unit/studio/src/ui/ButtonGroup.test.js
test/unit/studio/src/ui/ButtonSelectorGui.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindow/preferencesButton.test.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowBuildView/EntryPointPopover.test.js

feat: Improved build view entry point system

---

studio/src/preferences/PreferencesManager.js

When trying to vendor Renda files from a url like raw.githubusercontent.com or deno.land/x, it will fail due to deno parsing the entire module tree, including type imports.
It fails because of css import assertions, and because of some import paths that were using .js instead of .ts.
Unfortunately, there's not much we can do about css import assertions. Whoever tries to vendor it will have to add `studioStyles.js` and `shadowStyles.js` to their import map and point it to an empty file.
But the .js file extensions we can fix, since TS supports .ts imports now.

fix: import types from types.ts instead of types.js to fix deno vendor errors

---

src/inspector/InternalDiscoveryManager.js
src/util/TypedMessenger.js
studio/src/misc/ServiceWorkerManager.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryIframeMain.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryWorkerMain.js
studio/src/tasks/task/TaskBuildApplication.js
studio/src/tasks/task/TaskBundleAssets.js
studio/src/tasks/task/TaskBundleScripts.js
studio/src/tasks/workers/buildApplication/mod.js
studio/src/tasks/workers/bundleAssets/mod.js
studio/src/tasks/workers/bundleScripts/mod.js
studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.js
studio/sw.js
test/unit/src/inspector/InternalDiscoveryManager.test.js
test/unit/src/util/TypedMessenger/TypedMessenger.test.js
test/unit/src/util/TypedMessenger/shared/workerWithInitialize.js
test/unit/studio/src/tasks/TaskManager.test.js
test/unit/studio/src/tasks/shared/basicWorker.js
test/unit/studio/src/windowManagement/contentWindows/ContentWindowBuildView/ContentWindowBuildView.test.js

I think it makes more sense for TypedMessengers to take its own handlers first and the handlers of the other messenger after that.

feat!: Swap the TypedMessenger generic parameters

---

src/util/TypedMessenger.js

This prevented `deno vendor` from working correctly. See https://github.com/denoland/deno/issues/20172

fix: Remove jsdoc example with import statement

---

test/e2e/studio/src/windowManagement/contentWindows/ContentWindowOutliner.test.js

We'll disable it for now until #769 is fixed

test: Disable outliner e2e test

---

src/inspector/InternalDiscoveryManager.js
src/util/TypedMessenger.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryIframeMain.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryWorkerMain.js
studio/src/tasks/workers/bundleAssets/bundle.js
test/unit/src/util/TypedMessenger/TypedMessenger.test.js
test/unit/src/util/TypedMessenger/shared/workerWithInitialize.js

When the other end of the connection is untrusted, we can't assume that they will always respond to every request.
And even if the other end is trusted, the connection might still drop before the typedmessenger is destroyed.
This change adds two options:
- a `globalTimeout` option in the constructor of the `TypedMessenger`, or the `TypedMessenger.globalTimeout` value which can be modified directly.
- `TypedMessenger.sendWithTransfer` is now renamed to `TypedMessenger.sendWithOptions` and a timeout can be provided for specific requests.

feat: Add timeout options to TypedMessenger

---

src/util/TypedMessenger.js

Not really sure why this was here in the first place.
I think the idea was to make autocompletions for `setResponseHandlers()` work or something.
Either way, this doesn't seem necessary anymore now, and in fact was causing some issues while working on #800.
Specifically, I was trying to pass an existing generic argument to the TypedMessenger, something like:
```js
/**
* @template {TypedMessengerSignatures} TRes
* @template {TypedMessengerSignatures} TReq
* @param {TRes}
*/
function createMessenger(responseHandlers) {
/** @type {TypedMessenger<TRes, TReq> */
const messenger = new TypedMessenger();
messenger.setResponseHandlers(responseHandlers);
//                            ^^^^^^^^^^^^^^^^
//               'TRes' is not assignable to parameter of type 'ResponseHandlers'
}
```

refactor(TypedMessenger): Remove old type for responsehandlers

---

src/util/TypedMessenger.js
test/unit/src/util/TypedMessenger/TypedMessenger.test.js
test/unit/src/util/TypedMessenger/initializeWebSocket.test.js

With this change, `initializeWebSocket()` buffers messages until the connection is open.
I think you'd basically always want this to be the behaviour, but for some reason you'd want sending to fail when the socket isn't open yet, we could possibly πadd an option to `initializeWebSocket()` in the future.

feat(TypedMessenger): Don't send websocket messages before the connection is open

---

test/unit/src/util/binarySerialization/unions.test.js

This will probably be fixed by #275 as well.

test: Add binary serialization test for unions of an object and null

---

src/core/Entity.js
test/unit/src/core/Entity/hierarchy.test.js

fix(Entity): Allow filtering the root when using traverseDown or traverseUp

---

.github/workflows/ci.yml

Reverts rendajs/Renda#869
It seems like this is causing an error when uploading results from commits:
> There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Could not find a repository associated with upload token ***', code='not_found')}
https://github.com/rendajs/Renda/actions/runs/8217264270/job/22472772275

Revert "chore: Add codecov upload token"

---

src/core/MeshAttributeBuffer.js
test/unit/src/core/MeshAttributeBuffer/MeshAttributeBuffer.test.js

fix(Mesh): Don't throw when changing vertexcount to a lower value

---

src/network/studioConnections/discoveryMethods/InternalDiscoveryMethod.js
studio/src/misc/ServiceWorkerManager.js
studio/src/network/studioConnections/internalDiscovery/internalDiscoveryIframeMain.js
test/unit/src/network/studioConnections/ParentStudioCommunicator.test.js
test/unit/src/network/studioConnections/discoveryMethods/InternalDiscoveryMethod.test.js
test/unit/studio/src/misc/ServiceWorkerManager.test.js

This appears to be functionally the same as the 'unload' event, except that this one isn't deprecated. An extra bonus is that 'beforeunload' doesn't deduct points from the 'best practices' section in lighthouse.

refactor: Use beforeunload event instead of unload

---

.github/workflows/ci.yml

I think this may be required before #925 can be merged

chore: Add id-token permissions for unit tests job

---

src/util/SingleInstancePromise.js
test/unit/src/util/SingleInstancePromise.test.js

fix(SingleInstancePromise): Make run() reject when the function rejects
